### ISSUE TITLE
Race condition?

### ISSUE THREAD

**Issue by darakanoit** [square1-io/laravel-idempotency#1]
Hi, can you tell me how requests are processed if a race condition has occurred? For example, 2 requests came over http at the same time, in one second and the cache for a second response is not ready yet.

**Comment by conroyp** [comment]
@darakanoit good catch! At the moment under that race condition, the cache for the second response won't be ready yet. I'm testing a branch at the moment which should sort this out via locking, it should be released in the next week, hopefully.

**Comment by pratikkuikel** [comment]
@darakanoit @conroyp I need some help here.
The cache is based on idempotency_key right ?
And the race condition occurs when the request with same key arrives at the same time ?
Race condition is not an issue if the idempotency_key is different but accessing that same resource ?

**Comment by conroyp** [comment]
@pratikkuikel that's exactly right - if your client is generating different idempotency keys for each request this isn't an issue. It becomes a problem if a race condition exists between two requests sent with the same idempotency key. So the use case here is something like the same request being sent twice by the browser, with network conditions meaning both hit at exactly the same moment.

**Comment by pratikkuikel** [comment]
@conroyp Got it. Thanks, I am new to cache locks.
And how can this condition be mitigated ? something to do with database layer or just cache locking would work ?

**Comment by conroyp** [comment]
@pratikkuikel from a package level, cache locking looks like a better approach than trying to go to the db, as it tends to be a little quicker to grab the lock. Work in progress on that update at the moment.

**Comment by conroyp** [comment]
@pratikkuikel @darakanoit I've just tagged [1.1.0](https://github.com/square1-io/laravel-idempotency/releases/tag/1.1.0), which should help avoid these race conditions in the case of re-used idempotency keys from competing requests.
